### ISSUE TITLE
Completely broke on my server after the first map

### ISSUE THREAD

**Issue by ZachPL** [blastehh/AnotherULXSBanModule#1]
L 04/16/2015 - 18:32:53: [SBAN][ERROR] Table 'sourcebans.player_data' doesn't exist
L 04/16/2015 - 18:32:53: [SBAN][ERROR] SELECT sid64, name FROM player_data WHERE sid64 = '76561198040333019'
L 04/16/2015 - 18:32:53: [SBAN][Init] Mysql failed to connect
L 04/16/2015 - 18:32:53: [SBAN][Init] Mysql Error: This handle is already connected. Use a separate handle for each connection.
L 04/16/2015 - 18:32:53: Lua Error: [SBAN] Re-connection to database server failed.

L 04/16/2015 - 18:33:46: [SBAN] Query is empty?
L 04/16/2015 - 18:33:46: Lua Error: [SBAN] Empty query, retrying connection.

Saw these errors in console, I went back to FunDK's for now as bans were not posting to sourcebans and banned players could rejoin.

**Comment by blastehh** [comment]
Fixed by removing some custom code that I had integrated with my own servers.

https://github.com/blastehh/AnotherULXSBanModule/commit/c23cec1451e9b71c89f39e9c8c8d83ad3e443f54
