### ISSUE TITLE
Error with group not existing

### ISSUE THREAD

**Issue by ZachPL** [blastehh/AnotherULXSBanModule#11]
If a group doesn't exist in ulx but does in sourcebans and someone is assigned to it and then joins the server it produces an error,

L 03/30/2016 - 13:10:22: Lua Error: 
[ERROR] addons/ulib/lua/ulib/shared/hook.lua:110: addons/ulx/lua/ulx/modules/sh/user.lua:74: Group does not exist for adding user to (CS Premium Plus (Sub))
1. fn - [C]:-1
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

I don't really want to create this group as we use this group for CSGO only and not gmod, so it it possible to fix this so that it doesn't error.

Thanks.

**Comment by blastehh** [comment]
Not a bug
