### ISSUE TITLE
Sourcebans Group Overriding ULX Group

### ISSUE THREAD

**Issue by Violat0r** [blastehh/AnotherULXSBanModule#13]
In SourceBans, an admin is set to "Admin" as the server admin group with the server ticked inside Admin Server Access and in game is set to superadmin via ulx users.txt. The SBan module will override that superadmin in ulx's users.txt with "Admin" from sourcebans even though removeFromGroup is set to false and superadmin is one of the excludedGroups.

**Comment by blastehh** [comment]
Is it adding them to "Admin" group on the server?

**Comment by Violat0r** [comment]
Yes, overriding superadmin or any other rank on the server with whatever rank they may have in sourcebans if that server is ticked in that person's server access.

**Comment by blastehh** [comment]
Yes, granting access will override anything... just untick the server on
the website.

**Comment by Violat0r** [comment]
Is there anyway to include or change the module so this doesn't happen?

**Comment by blastehh** [comment]
replace line 410 with "if (ULib.ucl.getUserRegisteredID(ply) == nil or
ply:GetUserGroup() != group) or !excludedGroups[ply:GetUserGroup()] then"
in anotherulxsbanmodule/lua/ulx/modules/sban.lua

**Comment by Violat0r** [comment]
Thanks, I will give that a try.

**Comment by Violat0r** [comment]
Sadly, that did not work.

**Comment by Violat0r** [comment]
Commenting out ulx.adduserid(ply, steamid, group) did not stop it from setting the rank from sourcebans, it must be doing it by other means.

**Comment by Violat0r** [comment]
Correction, commenting out ulx.adduserid(ply, steamid, group) does stop it but it seems like !excludedGroups[ply:GetUserGroup()] doesn't work.

**Comment by blastehh** [comment]
I used or instead of and: "if (ULib.ucl.getUserRegisteredID(ply) == nil or
ply:GetUserGroup() != group) and !excludedGroups[ply:GetUserGroup()] then"

**Comment by blastehh** [comment]
This will break the normal functionality of the addon though, use it at
your own choice.
If you want to change the group of an existing user, and their current
group is in the excluded list, you'll have to do it manually.

**Comment by Violat0r** [comment]
I understand, that did do the trick to fit my communities needs, thank you for your help it is much appreciated.
