### ISSUE TITLE
What is this about?

### ISSUE THREAD

**Issue by matiasg90** [blastehh/AnotherULXSBanModule#5]
1
![](https://i.gyazo.com/ec748a78b7905df689cf7fd8bcca6ad1.png)
![](https://i.gyazo.com/268e34103c08fd8c1a80391654e4492d.png)

2
![](https://i.gyazo.com/82b838fb73bb7aada8c9e7ab81bad60e.png)

**Comment by blastehh** [comment]
1. You've cut out the rest of the error message
2. That's when a family sharing check fails due to steam. There's no way to get a better error message because gmod doesn't provide it.
   Either ignore it or disable family sharing check.
