### ISSUE TITLE
Broken ever since February

### ISSUE THREAD

**Issue by iamgiygas** [blastehh/AnotherULXSBanModule#8]
Okay, tmysql and psmysql aren't working for me, with this. tmysql and plib (that includes pmysql) causes a server hang if I put it into the lua/bin folder and the wrapper in lua/includes/modules. If I put plib (pmysql and more) and tmysql into a folder in the addons directory, I get spammed with errors and Sourcebans just doesn't work.

http://pastebin.com/KqGZ4J7e

**Comment by blastehh** [comment]
Use the version of pmysql on my github

**Comment by iamgiygas** [comment]
Sourcebans still errors.

**Comment by blastehh** [comment]
You didn't install correctly or you messed up the configuration

**Comment by iamgiygas** [comment]
Okay, so... 
the tmysql DLL file goes into lua/bin
the "mysqloo.lua" from tmysql goes in lua/includes/modules
and the "pmysql" from your github goes in lua/includes/modules
Right? Am I missing anything?
